/*
 * Oracle Utilities REST API for Work and Asset
 * This documentation helps you to get started using the REST APIs for Oracle Utilities Work and Asset Cloud Service and Oracle Utilities Work and Asset Management.
 *
 * OpenAPI spec version: 2021.12.08-oas3-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InventoryStockItemsApi
 */
@Ignore
public class InventoryStockItemsApiTest {

    private final InventoryStockItemsApi api = new InventoryStockItemsApi();

    
    /**
     * Synchronize Stock Item
     *
     * A stock item sync request record manages the creation or update of a stock item.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void syncTest() throws Exception {
        api.sync();

        // TODO: test validations
    }
    
}
