/*
 * Oracle Utilities REST API for Work and Asset
 * This documentation helps you to get started using the REST APIs for Oracle Utilities Work and Asset Cloud Service and Oracle Utilities Work and Asset Management.
 *
 * OpenAPI spec version: 2021.12.08-oas3-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PurchasingVendorsApi
 */
@Ignore
public class PurchasingVendorsApiTest {

    private final PurchasingVendorsApi api = new PurchasingVendorsApi();

    
    /**
     * Synchronize Vendor Location
     *
     * This REST service synchronizes Enterprise Resource Planning (ERP) Suppliers with Work and Asset Management Vendor and Vendor Locations, by creating Work and Asset Management Vendor Location Data Synchronization objects.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void syncVendorLocationTest() throws Exception {
        api.syncVendorLocation();

        // TODO: test validations
    }
    
}
