/*
 * Oracle Utilities REST API for Work and Asset
 * This documentation helps you to get started using the REST APIs for Oracle Utilities Work and Asset Cloud Service and Oracle Utilities Work and Asset Management.
 *
 * OpenAPI spec version: 2021.12.08-oas3-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WorkActivityApi
 */
@Ignore
public class WorkActivityApiTest {

    private final WorkActivityApi api = new WorkActivityApi();

    
    /**
     * Get Work Activity
     *
     * Retrieves activity details for project planning, not including attachments.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void w1PrjActDtlTest() throws Exception {
        Object activityId = null;
        api.w1PrjActDtl(activityId);

        // TODO: test validations
    }
    
    /**
     * Patch Work Activity Schedule Window
     *
     * Updates the scheduling window of activities. There is a work window start date/time through a work window end date/time that can be updated from other external systems that manage enterprise project planning.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void w1UpdSchWinTest() throws Exception {
        Object activityId = null;
        api.w1UpdSchWin(activityId);

        // TODO: test validations
    }
    
}
